In [13]:
from tqdm import tqdm
import pandas as pd
import spacy
import re
import unicodedata
from unidecode import unidecode
import ast
from collections import Counter

In [14]:
pd.set_option('display.max_columns', 30)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [ ]:
ents = pd.read_csv("/Users/pol/Downloads/extracted_ents_ALL.csv", sep=';')
ents = ents.dropna(subset=["name"])
ents

press = pd.read_csv("/Users/pol/Downloads/agg_matches_ALL.csv", sep=';')
press

,article_id,article_text,name,name_count
0,1,Serge Reggiani - Succès & confidences .\n Une ...,"['Serge Reggiani - Succès & confidences', 'Reg...",1
1,2,"Désolés, Warren .\n C'est une maigre consolati...","['Warren', 'Warren Zevon', ""I'll sleep when I'...",10
2,3,Adam Green - Friends of mine .\n Dire qu'on a ...,"['Adam Green - Friends of mine', 'The Kills', ...",1
3,4,Cesaria Evora - Voz d'amor .\n Dès les premièr...,"['gorgée', 'Voz', ""Voix de l'amour"", 'Velocida...",2
4,5,Herman Düne - Mas cambios et Mash Concrete Met...,"['Herman Düne - Mas cambios', 'Mash Concrete M...",1
...,...,...,...,...
52639,52690,"Rap, jazz, rock, classique, chanson… Les album...","['Rap', 'Monde', 'An Evening with Silk Sonic',...",45
52640,52691,Que sait-on vraiment des surrisques de contami...,"['Covid-19', 'Omicron', 'Jean Castex', 'Covid-...",482
52641,52692,"Rencontre avec Riccardo Muti, maestro à vie .\...","['Riccardo Muti', 'Riccardo Muti', 'Cristina',...",70
52642,52693,Ils sont passés chez Colors : la sélection mus...,"['Colors', 'Monde Afrique', 'Le Monde Afrique'...",27
52643,52694,Musique : des enregistrements historiques venu...,"['Pierre-Emmanuel Barbier', 'Thomson', 'Diapas...",1

### check texts with possible false positives

In [70]:
count = 0

for i, (text, namelist) in enumerate(
    zip(press["article_text"],
        press["name"]
        )):
    if ("'Johnny Cash'" in namelist and "'Johnny'"):
        #print(i)
        count += 1

print(count)

220

In [7]:
press["name"] = press["name"].apply(ast.literal_eval)
press["name"]

0        [Serge Reggiani - Succès & confidences, Reggia...
1        [Warren, Warren Zevon, I'll sleep when I'm dea...
2        [Adam Green - Friends of mine, The Kills, Gree...
3        [gorgée, Voz, Voix de l'amour, Velocidade, Ces...
4        [Herman Düne - Mas cambios, Mash Concrete Meta...
                               ...
52639    [Rap, Monde, An Evening with Silk Sonic, Silk ...
52640    [Covid-19, Omicron, Jean Castex, Covid-19, Clu...
52641    [Riccardo Muti, Riccardo Muti, Cristina, Ricca...
52642    [Colors, Monde Afrique, Le Monde Afrique, Colo...
52643    [Pierre-Emmanuel Barbier, Thomson, Diapason, P...
Name: name, Length: 52644, dtype: object

In [71]:
def count_name_cooc(target_name, position="first"):
    """
    namelists: iterable of lists of extracted names
    target_name: string (e.g. "christophe" or "mae")
    position: "first" or "last"
    """

    target_name = target_name.lower()
    alone_count = 0
    cooccurrence_counter = Counter()

    for namelist in press["name"]:

        names_lower = [n.lower() for n in namelist]

        # Case 1: FIRST NAME logic
        if position == "first":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.startswith(target_name + " ")]

            if has_alone and not full_names:
                alone_count += 1

            elif has_alone and full_names:
                for full_name in full_names:
                    last_part = full_name[len(target_name)+1:]
                    cooccurrence_counter[last_part] += 1

        # Case 2: LAST NAME logic
        elif position == "last":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.endswith(" " + target_name)]

            if has_alone and not full_names:
                alone_count += 1

            elif has_alone and full_names:
                for full_name in full_names:
                    first_part = full_name[:-(len(target_name)+1)]
                    cooccurrence_counter[first_part] += 1

        else:
            raise ValueError("position must be 'first' or 'last'")

    return alone_count, cooccurrence_counter

In [24]:
from collections import Counter
import re

def count_name_cooc(target_name, position="FIRST", window=10, mode="words"):
    """
    target_name: string (e.g. "jackson")
    position: "first" or "last"
    window: number of words before/after (used if mode="words")
    mode: "words" or "sentence"
    """

    target_name = target_name.lower()
    alone_count = 0
    cooccurrence_counter = Counter()
    contexts = []  # list of tuples: (article_id, context)

    for article_id, namelist, article_text in zip(
        press["article_id"], 
        press["name"], 
        press["article_text"]
    ):

        names_lower = [n.lower() for n in namelist]
        text_lower = article_text.lower()

        # -------- Determine logic --------
        if position == "FIRST":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.startswith(target_name + " ")]

        elif position == "LAST":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.endswith(" " + target_name)]

        else:
            raise ValueError("position must be 'first' or 'last'")

        # -------- CASE 1: NAME ALONE --------
        if has_alone and not full_names:
            alone_count += 1

            context_found = None

            if mode == "sentence":
                sentences = re.split(r'(?<=[.!?])\s+', article_text)
                for s in sentences:
                    if target_name in s.lower():
                        context_found = s.strip()
                        break  # only first sentence

            elif mode == "words":
                words = article_text.split()
                words_lower = [re.sub(r'\W+', '', w.lower()) for w in words]

                for i, w in enumerate(words_lower):
                    if w == target_name:
                        start = max(0, i - window)
                        end = min(len(words), i + window + 1)
                        context_found = " ".join(words[start:end])
                        break  # only first match

            if context_found:
                # Highlight name
                context_found = re.sub(
                    rf"\b({target_name})\b",
                    lambda m: m.group(1).upper(),
                    context_found,
                    flags=re.IGNORECASE
                )

                contexts.append((article_id, context_found))

        # -------- CASE 2: NAME WITH OTHER PART --------
        elif has_alone and full_names:
            for full_name in full_names:
                if position == "first":
                    last_part = full_name[len(target_name)+1:]
                    cooccurrence_counter[last_part] += 1
                else:
                    first_part = full_name[:-(len(target_name)+1)]
                    cooccurrence_counter[first_part] += 1

    return alone_count, cooccurrence_counter, contexts

In [49]:
target_name = "VICE"

alone, with_last, contexts = count_name_cooc(
    target_name=target_name,
    position="LAST",
    window=24,
    mode="words"
)

print("Alone count:", alone)
print("\nTop co-occurring names:\n")

for k, v in with_last.most_common(10):
    print(f"{k}: {v}")

print("\nContexts:\n")

for article_id, snippet in contexts:
    print(f"[Article {article_id}]")
    print(snippet)
    print()

Alone count: 53

Top co-occurring names:


Contexts:

[Article 8206]
cinéma, comment avez-vous réussi à le convaincre de revenir jouer pour vous ? C'est grâce à Paul Thomas Anderson avec qui il tourne actuellement VICE caché. Il a été très persuasif et a réussi à le convaincre. Je savais que Joaquin était dans une mauvaise passe et qu'il voulait

[Article 10159]
tout de noir vêtu, avec un col montant blanc (Niels Arestrup) et Fouché, dans un bel habit à broderies d'argent (costumes Nathalie Bérard-Benoin). Le VICE et le crime Jean-Claude Brisville, qui avait déjà composé L'Entretien entre M. Descartes et M. Pascal le jeune, reprenait cette dramaturgie pour Le Souper

[Article 14813]
Gary Hart, la débandade . Pour jouer Dick Cheney dans VICE (en salle le 20 février), Christian Bale a pris du poids et s'est fait une tête de chauve. Hugh Jackman, lui, n'a besoin que

[Article 14948]
Paris, on découvre le réalisateur de The Big Short, formé au théâtre d'improvisation à Chicago, allongé sur le canapé de sa chambre d'hôtel. Avec VICE, le cinéaste oscarisé, surtout connu pour sa collaboration avec Will Ferrell, sait qu'il a frappé fort. Il s'en explique au Figaro, sans détours. LE

[Article 14951]
« VICE » : un Dick Cheney massif . Ça n'était pas gagné. Au départ, il y a un étudiant irresponsable qui prend des cuites terribles

[Article 14990]
reptilien, il regarde son ancienne victime, qu'il tutoie toujours. L'acteur a une telle présence qu'il pourrait jouer Le Pen dans un biopic à la VICE, si ce genre de film était possible en France. Il faut féliciter Ozon d'avoir foncé. L'affaire est en cours de jugement. D'autres abusés se

[Article 15017]
effets visuels, du montage son. Pourquoi pas de l'affiche ou de la bande-annonce pendant qu'on y est ? Côté coup de pied de l'âne, VICE fut couronné pour les maquillages et les coiffures. C'est d'un vexant pour Dick Cheney. C'est bien la peine d'avoir dirigé en sous-main le pays

[Article 15098]
euros. Il n'est pas trop tard pour (re)voir Greenbook : Sur les routes du Sud, Grâce à Dieu, Le Chant du loup, La Favorite, VICE, La Mule, Marie Stuart, reine d'Écosse, Les Éternels, La Flor, partie 1, Stan & Ollie, Convoi exceptionnel... Un pharaon en or Quelque 130 000

[Article 16480]
Tomer Sisley avoue avoir « hâte de retourner travailler. La pandémie a reporté le film que je devais tourner à Boston pour Adam McKay (VICE, NDLR) en juin mais vont-ils garder les acteurs européens qui pour l'instant ne peuvent pas voyager ? Je vais tourner une série avec Julie

[Article 22428]
Romans étrangers : - William Boyd pour Orages ordinaire» (Seuil) - Grande-Bretagne - Sofi Oksanen pour Purge (Stock) - Finlande - Thomas Pynchon pour VICE caché (Seuil) - Etats-Unis - Gonçalo Tavares pour Apprendre à prier à l'ère de la technique (Viviane Hamy) - Portugal - David Trueba pour

[Article 22647]
dans des lieux toujours différents ou des événements Dimuschi dont on ne connaît le lieu qu'au dernier moment. Des revues indépendantes s'y mettent aussi. VICE a investi des bars de quartier dans des soirées Rades et le magazine trimestriel Entrisme organise des concerts ou des DJ sets dans des

[Article 24003]
Outil de communication et unité de production (à travers un studio virtuel), The Creators Project a vu le jour grâce au groupe de presse VICE et au géant de l'informatique Intel. Neuf projets ainsi labellisés à Coachella donnaient une idée concrète de l'initiative. En marge du tumulte, on pouvait

[Article 27135]
En 2009, à 74 ans et déjà bien affaibli par la neuropathie, c'est avec délectation que Crews décrivait la dernière en date, au magazine VICE : «Elle est très belle. Elle part de mon pubis et traverse mon nombril pour remonter jusqu'au sternum, où elle finit à équidistance des

[Article 27816]
contemporaine, tant dans l'architecture que le design, l'art, la musique, la mode ou le jeu vidéo. Fanzine. Drôle d'accouplement que ce projet piloté par VICE, fanzine irrévérencieux créé en 1994, devenu empire médiatique, présent dans une trentaine de pays et entièrement financé par le géant du microprocesseur Intel, qui

[Article 28364]
y a quelques jours. «Une baleine blanche, un serpent de mer» Qui sera heureux, le jour de son anniversaire, de recevoir à la fois VICE caché, Vineland, et V. ? «Le désert envahit la terre de l'homme subrepticement», écrit Pynchon. «Bientôt, il n'y aura rien. Bientôt, le désert, seulement.»

[Article 29004]
de «la Gaga» en la singeant en goguette dans une Afrique pleine de clichés, elle s'énerve. Dans le clip Fatty Boom Boom coproduit par VICE, on la découvre, habillée de ses côtelettes fétiches, cliente d'un safari urbain, opérée pour un insecte bloquée dans ses parties intimes, et finalement dévorée

[Article 31640]
la performance aurait été appelée "l'Artiste n'est pas présent" et on en aurait parlé dans les revues d'art.» Mais pour Noisey, l'appendice du magazine VICE dédié à la musique, la dernière provocation de Death Grips les place au niveau d'un «ado défoncé qui porte un tee-shirt Anarchy acheté dans

[Article 31965]
la liberté et de la révolution, sous la forme de vidéos, de musique, de poésie et de photographie». Le tout sponsorisé par le groupe VICE (sic) et la plateforme de téléchargement BitTorrent (sic). Mardi soir, Madonna avait évidemment choisi de s'exprimer en musique dans une sorte de show gagesque,

[Article 32754]
Agnès B pour celle de son rutilant confrère, Emmanuel Perrotin ? Peut-il encore nous faire croire à tant d'innocence, le petit prodige soutenu par VICE et devenu en dix ans la coqueluche du monde de l'art, de la mode et des magazines ? Les immenses tirages chez Perrotin, tels

[Article 33017]
derrière des entrepôts, a pour ligne directrice le corps et ses représentations. Lundi, le photographe a shooté huit modèles parisiens volontaires pour le magazine VICE. De Pékin à Pantin, l'érotisme made in China fait du chemin.

[Article 33598]
Une fascination qui a un nom, le ruin porn, sarcasme lancé par un habitant de la ville, en juillet 2009, à un journaliste de VICE, venu faire un reportage sur ladite tocade. On regarderait donc les ruines comme on mate un porno, pour y trouver un plaisir immédiat et

[Article 33749]
regardons et comment nous le faisons, elle a aussi façonné la production des images. Wolfgang Tillmans, Ryan McGinley, les séries publiées dans le magazine VICE ou certains clichés publiés sur Tumblr : tout s'inscrit dans sa lignée. En montrant qu'un autre cadre, émotionnel, était possible, elle a modifié la

[Article 35897]
Noël sans les boules . De gauche à droite, pochette «Fire» en cuir, 245 €, Kenzo. Palette fards à paupières «VICE», 49€, Urban Decay chez Sephora. Basket en cuir et semelle en gomme, modèle «Spaceship» par Romain Kremer, 180 €, Camper. Cabas en cuir, 880

[Article 36487]
tendances et à la culture haut de gamme - comme The Creators Project, créée en 2009 par la marque Intel et le magazine new-yorkais VICE, ou Nowness, la plateforme créative de LVMH - multiplient en effet les collaborations : partenariat avec l'Opéra de Paris et le Royal Ballet de

[Article 37596]
et, exposé à un négatif, une image toute bleue aux motifs blancs apparaît soudain. «Série Blues» (Photo Tim Barber) Tim Barber, ancien iconographe chez VICE, créateur de la plateforme de talents Tinyvices, devenu depuis photographe, s'est essayé à cette technique. Ses images regroupées sous le titre Blues viennent toutes

[Article 37677]
dans Foxy Brown, film emblématique de la blaxploitation, Pam Grier planque un revolver dans sa gigantesque touffe. Et aujourd'hui ? En 2010, le magazine VICE interroge de jeunes Afro-Parisiennes. Comment trouventelles leurs cheveux au naturel ? Les réponses se ressemblent. Amy, 19 ans, les trouve «horribles». Tene, 28 ans

[Article 37743]
de soutien, et la page Facebook créée dans la journée est suivie par 2 000 personnes, détaillait-il récemment à Noisey, branche musicale du magazine VICE. Le prix des billets, variables selon les lieux et les groupes, oscillait entre 5 et 18 euros. Sans tête d'affiche à proprement parler –

[Article 38128]
différents supports, du smartphone à la tablette en passant par l'ordinateur classique. Le magazine de charme fait désormais face à d'autres publications irrévérencieuses, tel VICE, qui séduisent un public plus jeune, plutôt masculin et urbain, que Playboy va tenter de faire revenir dans son escarcelle. «La différence entre nous

[Article 38258]
sulfureux et tendance (1). Quelques signaux, au-delà des statuts Facebook saturés de viandes grillées. Gibier sur un plateau La presse masculine prétendument burnée, de VICE à Lui, remet la chasse au goût du jour, forme de retour viril à la nature pour citadins aseptisés. Cet hiver, on ne s'étonnera

[Article 38401]
L’entretien des Eagles of Death Metal par «VICE» : l’émotion à show . Samedi dernier, VICE, l'ancien magazine punk canadien devenu en un peu plus de deux décennies un mastodonte médiatique international,

[Article 38473]
et 64 «bitch» dans Straight outta Compton de NWA). A quoi s'ajoute, chaque année, l'intervention d'un contradicteur (des journalistes du NY Times, de MTV, VICE, Grantland, Rolling Stones) invité à défendre un autre morceau clé, puisqu'il y a toujours matière à débat dans le seul fait de dresser des

[Article 38674]
de reconstruction et d'opprobre. Yamamoto expose et fait défiler ses créations à Londres en mai 1971. Bowie est subjugué. Yamamoto a raconté au magazine VICE comment il avait découvert l'artiste arborant ses créations lors d'un concert au Radio City Hall de New York en 1972. Il a été bluffé.

[Article 39978]
détours étudiants en galère, stagiaires perpétuels et hédonistes impénitents, La Femme donne de la voix et de la poésie à la jeunesse qui lit VICE et Nietzsche, Brain et Frédéric Lordon ou qui ne lit rien du tout par dépit de quelque chose, à laquelle on n'ose pas s'adresser

[Article 40400]
américaine Jennifer Lawrence, 26 ans, a choisi de s'exprimer sur la question, à travers une lettre ouverte publiée sur Broadly, le site féministe de VICE. Dans cette lettre, la star oscarisée ne minimise pas sa stupeur, tout en insistant plutôt sur le fait que, désormais, il importe plus que

[Article 40599]
où Mariah Carey met tout le monde d’accord. Deux exemples en témoignent encore pour cette année : le magazine ultra-branché et d'habitude très moqueur VICE se penche sur All I Want For Christmas Is You pour expliquer sérieusement pourquoi il s'agit de la chanson de Noël la plus addictive.

[Article 41318]
commencent souvent la conversation en prévenant : «Je ne sais pas si c'est un viol, mais…» Alexandra Brodsky, citée par le site Broadly de VICE, explique s'être intéressée au phénomène alors qu'elle était étudiante en fac de droit il y a quatre ans, après avoir eu vent sur le

[Article 41722]
réalité d'un faux site créé le 29 juin 2017 qui ressemble comme deux gouttes d'eau au vrai, le Hollywood Reporter (et non Reported). D'après VICE, cette page a été créée de toutes pièces par Sony Music, qui gère Columbia Records, le label d'Arcade Fire. Label qui sort le nouvel

[Article 41824]
Tels pères tel «VICE» . En 1994, VICE n'est encore que Voice of Montreal, un fanzine gratuit rédigé par deux punks, Suroosh Alvi, toxicomane en sevrage, et Gavin

[Article 42009]
France (où elle a été diffusée sous le nom de Larry et son nombril), il n'en est rien aux Etats-Unis où le site de VICE allait jusqu'à expliquer en juillet en quoi Curb Your Enthusiasm s'imposait comme un guide de survie majeur en ces temps troublés. Etrange titre en

[Article 42693]
principal) et Katja Blichfeld, sonde sans porter de jugement cette bulle progressiste qu'est Brooklyn et sa population - féministes radicales, Juifs hassidiques, pigistes pour VICE – attachante, irritante et «psychotropée». Le charme de High Maintenance réside surtout dans sa narration qui, à l'image de son personnage principal, flâne tranquillement

[Article 44260]
la mode et les jeunes galeries. Courtisé par les magazines, les éditeurs, les agents, les galeries, les musées, invitations et publications se multiplient. Capricious, VICE, Purple Fashion, Dune Magazine, Antidote, Néon, lui commandent des séries photos. Carine Dolek, qui s'est occupée de la communication de sa première exposition en

[Article 44312]
dark metal de Michael Moynihan et Didrik Søderlind (déjà 7 000 exemplaires vendus), cartonnera cette année à cause de son adaptation en film par VICE. Pour Jacques Gros, «Camion blanc a toujours un coup d'avance. Ils viennent par exemple de publier une bio de Thurston Moore. On peut leur

[Article 45339]
eu un vrai impact. Générations et le Mouv' ont surenchéri. Mais, aujourd'hui, c'est Internet qui donne le la.» Journaliste freelance au Mouv' et chez VICE, Yérim Sar pense au contraire qu'«avec ou sans Skyrock, le rap se serait développé en France». «Pour moi, Skyrock s'est engouffré dans la brèche

[Article 45496]
est vertigineux. PNL Deux Frères (QLF) Le troisième membre (fantôme) de PNL est leur ingénieur du son, Nikola Feve (aka nk.f). Dans le magazine VICE, il raconte la cuisson lente de Deux Frères : «On a passé un temps monstre en post-production, c'était interminable, on écoutait l'album syllabe par

[Article 45717]
on constate la dissonance. On veut bien croire que le pilier de pub intimidant, lunettes noires sur le nez, que décrivait un journaliste de VICE dans une interview de 2017 a bel et bien existé, mais ce n'est pas lui qui répond à nos questions. «Conversation doesn't run dry,

[Article 47555]
une proportion qui aura peut-être échappé à quelques-uns, mais Crystallmess (vrai nom Christelle Oyiri, repérée à l’époque où elle faisait encore du journalisme pour VICE ou The Fader) est aussi une énergumène paradoxale en son royaume. De look, d’attitude, d’aplomb, rien ne colle avec ce qui fait sens ou

[Article 48342]
laquelle tu deviens vraiment une blague virale n'est jamais loin. Dans une des premières interviews dans son costume de Ninja, Tudor Jones expliquait à VICE en 2008 que ""jamais personne venant d'Afrique du Sud n'avait marché de l'autre coté de l'océan"". La preuve que non, puisque si l'univers fonctionne

[Article 49201]
Les Eagles of Death Metal se confient au magazine « VICE » . De retour aux Etats-Unis après les attentats du vendredi 13 novembre, les membres du groupe de rock Eagles of Death Metal, avaient

[Article 49216]
être le premier groupe à jouer au Bataclan quand il rouvrira », avait ensuite assuré le chanteur Jesse Hughes dans une interview au site VICE, promettant de revenir à Paris. Josh Homme, le co-fondateur des Eagles of Death Metal, qui n’était pas au concert du Bataclan, sera présent sur

[Article 49403]
1 200, c’est insultant » a, lui, agrémenté ses comptes d’un A entouré d’un cercle, le symbole anarchiste, et a expliqué sur le site VICE : « Y’a quand même une assez grande inégalité des salaires. C’est dans ce sens-là que je le dis, et surtout pas pour blâmer

[Article 49627]
la meilleure scène punk du pays en ce moment ») proclamait en février 2014 le magazine Noisey, l’un des titres du groupe de médias VICE. Un pied dans le punk, l’autre dans la pop Punk donc avec les quatre musiciens Beach Slang sur la Grande Scène pour entrer, samedi

[Article 51552]
du rap rital, de Salmo à Mahmood : le galopin galope à fond de train. Et incognito. L’unique interview qu’il a accordée, au webzine VICE, remonte à avril 2018. Quant à ses vidéoclips, ils le représentent sous la forme d’un personnage de cartoon, blouson noir et sweat violet à

[Article 52261]
1, 2 et 3, et le dernier, High et Fines Herbes, du même nom que leur émission gastronomique (diffusée d’abord sur YouTube puis sur VICE) et que leur livre de recettes proposant leur cuisine relevée au cannabis. Véritable Method Man et Redman du rap francophone, ils ont développé un

In [57]:
count_name_cooc(target_name=target_name,
    position="first")

(0, Counter(), [])

In [103]:
n = 10                       
count = 0
artist = "ziggy stardust"

for i, (text, namelist) in enumerate(zip(press["article_text"],
                                         press["name"])):
    if artist in namelist:
        print(i)
        print(namelist)
        print("-------------------")
        print(text)
        print("===================")

        count += 1

print(f"{count} OCCURRENCES OF '{artist}'")

0 OCCURRENCES OF 'ziggy stardust'

In [ ]:
n = 10                       
count = 0
artist = "ziggy stardust"

for i, (text, namelist) in enumerate(zip(press["article_text"],
                                         press["name"])):
    if artist in namelist:
        # split the article into tokens and look for the artist token(s)
        words = text.split()
        for idx, w in enumerate(words):
            if w.lower() == artist.lower():
                lo = max(0, idx - n)
                hi = idx + n + 1
                snippet = " ".join(words[lo:hi])
                print("------------------------")
                print(i)
                print(namelist)
                print(snippet) # only n words before/after
        count += 1

print("==================")
print(f"{count} OCCURRENCES OF '{artist}'")

==================
0 OCCURRENCES OF ''ziggy stardust''

In [76]:
df = ents
len(df)

408677

In [98]:
df = ents

# normalize both texts
def clean_text(text):
    text = text.lower()
    text = unicodedata.normalize("NFKD", text)
    text = unidecode(text) # remove accents
    # text = text.replace("\xa0", " ")
    text = text.strip()
    return text


df = df[df["name"].map(len) > 2] # short names

df["name"] = df["name"].apply(clean_text)

### check names with many tokens

maybe leave for now, if we do strict matching they'll be dropped anyway

In [103]:
df = df.drop_duplicates(subset=["name"])
df.reset_index()

         index  name_id            name  name_count  article_id
0            2        3      liberation        3336         870
1            3        4          figaro        2749        1786
2            4        5        internet        2376          40
3            5        6          mozart        1831          87
4            6        7            dieu        1616         592
...        ...      ...             ...         ...         ...
386005  408671   408672    i'm changing           1       49038
386006  408672   408673       i'm blind           1       48689
386007  408673   408674     i'm amazing           1       49542
386008  408674   408675  i'm all smiles           1       50227
386009  408676   408677   i'll show you           1       49669

[386010 rows x 5 columns]

In [105]:
df.to_csv("/Users/pol/Downloads/extracted_ents_clean.csv", sep=';')

In [ ]:
# add french stopwords from spaCy
nlp = spacy.load("fr_core_news_lg", exclude=['tagger', 'parser', 'ner', 
                                            'attribute_ruler', 'lemmatizer']) # load the small French language model

french_stopwords = nlp.Defaults.stop_words # access stopwords list
french_stopwords = list(french_stopwords) # convert to list

In [44]:
namelist = [name.lower() for name in press["name"]]
namelist

["['serge reggiani - succès & confidences', 'reggiani', 'brel', 'barbara', 'ventura', 'dernier courrier', 'cd prod', 'jacques canetti', 'polydor', 'serge reggiani']",
 '[\'warren\', \'warren zevon\', "i\'ll sleep when i\'m dead", \'roland the headless\', \'thompson gunner\', \'lawyers\', \'guns and money\', "mohammed\'s radio", \'sentimental hygiene\', \'elton john us\', \'springsteen\', \'jackson browne\', \'r.e.m.\', \'hunter thompson\', \'tom mcguane\', \'werewolves of london\', \'scorsese\', \'tom cruise\', "la couleur de l\'argent", \'mutineer\', "hugo cassavetti \\n i\'ll sleep when i\'m dead", \'cd\', \'rhino\', \'the wind\', \'naïve\']',
 '[\'adam green - friends of mine\', \'the kills\', \'green\', \'moldy peaches\', \'friends of mine\', \'bungee\', \'jonathan richman\', \'lou reed\', \'charles trenet\', "rubik\'", \'françois gorin\', \'cd pias\']',
 '[\'gorgée\', \'voz\', "voix de l\'amour", \'velocidade\', \'cesaria\', \'luis morais\', \'verte campagne\', \'greenfields\', \'brothers fours\', \'teofilo chantre\', \'eliane azoulay\', \'cd bmg\']',
 "['herman düne - mas cambios', 'mash concrete metal mushroom', 'herman düne', 'julie doiron from canada', 'diane cluck', 'cd', 'andré', 'david-ivar', 'neil young', 'françois gorin', 'cd track & field', 'cd shrimper']",
 "['albin', 'simone', 'souchon', 'boogaerts', 'télérama no 2800', 'souchon', 'boogaerts', 'albin', 'simone', 'souchon', 'patricia', 'arthur h', 'salif keita', 'angélique kidjo', 'jean-louis aubert', 'vassiliu', 'amour amitié', 'albin', 'simone', 'elle aime', 'tu es là', 'mambo déjeté', 'anne-marie paquotte', 'cd virgin']",
 '[\'ravel\', \'roger muraro\', \'alexandre tharaud\', \'assis\', \'andré suarès\', \'ravel\', \'gaspard\', \'miroirs\', \'sérénade grotesque\', \'le tombeau de couperin\', \'boléro\', \'liszt\', \'scarlatti\', \'debussy\', \'personnage secret\', "monfort-l\'amaury", \'alexandre tharaud\', \'roger muraro\', "jeux d\'eaux", "une barque sur l\'océan", \'roger muraro\', \'ravel\', \'ravel\', \'andré suarès\', \'roger muraro\', \'olivier messiaen\', \'oiseaux tristes\', \'tombeau\', \'gilles macassar \\n ravel\', \'roger muraro\', \'cd accord\', \'alexandre tharaud\', \'cd harmonia mundi\', \'fff\']',
 "['moutin reunion quartet - red moon', 'moutin', 'françois', 'louis', 'baptiste trotignon', 'rick margitza', 'miles davis', 'sylvain beuf', 'red moon', 'michel contat', 'cd nocturne', 'jvc jazz festival', 'new morning']",
 '[\'alexi tuomarila quartet\', \'festival tremplin\', \'brad mehldau\', \'alexi tuomarila\', \'prix du jury\', \'la buissonne\', \'ça\', \'warner\', \'brad mehldau\', "e.s.t. d\'esbjörn svensson", \'alexis tuomarila\', \'e.s.t. pas\', \'michel contat\', \'finlandia records\', \'warner\']',
 "['rca', 'latin', 'cuban carnival', 'tito puente', 'that cuban cha-cha-cha', 'fff', 'fff']",
 "['louis philippe', 'jonathan coe', 'climats', 'cd xiii bis records']",
 "['mozart - concertos', 'k. 482', 'k. 595', 'orchestre de chambre de lausanne', 'christian zacharias', 'ndr', 'gunter wand', 'david zinman', 'christian zacharias', 'orchestre de chambre de lausanne', 'daniel barenboïm', 'christoph eschenbach', 'don giovanni', 'leporello', 'zacharias', 'cd', 'g. m.', 'cd', 'mdg']",
 "['robert crumb - hot women', 'robert crumb', 'crumb', 'eliane azoulay', 'kein & aber/nocturne']",
 '[\'giovanni bononcini\', \'xviie\', \'haendel\', \'saxon\', "l\'ennemie de l\'amour faite amante -", \'bononcini\', \'clori\', \'tirsi\', \'monteverdi\', \'fileno\', \'acis\', \'galatée\', \'polyphème\', \'watteau\', \'verlaine\', \'bononcini\', \'archiluth\', \'ensemble 415 de la\', \'chiara banchini\', \'martin oro\', \'verlaine\', \'sagesse\', "un frisson d\'eau", \'gilles macassar\', \'giovanni bononcini\', "la nemica d\'amore fatta", \'serenata\', \'adriana fernandez\', \'martin oro\', \'furio zanasi\', \'cd zig-zag territoires\', \'harmonia mundi\']',
 '[\'yann tiersen - good bye lenin !\', \'yann tiersen\', "le fabuleux destin d\'amélie poulain", \'breton\', \'paddy mcaloon\', \'prefab sprout\', \'i trawl the megahertz\', \'kitchenware\', \'emi\', \'bo\', \'yann tiersen\', \'bo\', \'mc- aloon\', \'emmanuel tellier\', \'cd labels\', \'virgin\']',
 "['rca', 'cartola', 'martinho da vila', 'joão bosco', 'miucha', 'tom jobim', 'bmg', 'fff']",
 "['neil young - greendale', 'neil young', 'neil young', 'young', 'crazy horse', 'on the beach', 'cd', 'philippe barbot', 'cd reprise', 'warner']",
 "['cd le loup du faubourg', 'mélodie']",
 '["têtes raides - qu\'", \'variétélé\', \'johnny\', \'robert\', \'gratte poil\', \'têtes\', \'artaud\', \'soupault\', \'sûr\', \'têtes raides\', \'anne-marie paquotte\', \'cd\']',
 '["p\'tit jézu", \'piero moioli\', \'cd camayoc - distr\', \'mosaic music\', \'fff\']',
 "['jacques bertin', 'chansons & poètes', 'la jeune fille blonde', 'bertin', 'cd', 'epm', 'fff']",
 "['simone tassinot', 'chansons', 'caussimon', 'gainsbourg', 'le temps des cerises', 'leçon', 'cd le loup du faubourg - distr', 'mélodie']",
 "['super furry animals : phantom power', 'mario caldato jr', 'beastie boys', 'cd epic', 'fff']",
 '[\'rééditions soul\', \'gap band\', \'gloria scott\', \'undisputed truth\', \'çà\', \'stax\', \'mercury records\', "what\'s going on,", \'marvin gaye\', \'mercury records\', \'charles wilson\', \'gap band\', \'gloria scott\', \'ex-ikette\', \'ike\', \'tina turner\', \'barry white\', \'love unlimited\', \'barry white\', \'undisputed truth\', \'temptations\', \'norman whitfield\', \'staple singers\', \'stax\', \'stax\', \'otis redding\', \'wilson pickett\', \'rufus thomas\', \'isaac hayes\', \'hot buttered soul\', \'isaac hayes\', \'funky chicken\', \'rufus thomas\', \'remember\', \'otis redding\', \'the dock of the bay\', \'otis redding\', \'otis\', \'marie colmant\', \'rééditions stax\', \'warner\', \'mercury records\', \'universal\']',
 "['transe des gnaouas', 'world', 'essaouira festival gnaoua', 'moustapha bakbou', 'hamid el-kasri', 'hamida boussou', 'louis bertignac', 'julien lourau', 'bojan z', 'karim ziad', 'minino garay', 'amadou', 'mariam', 'les gnawa', 'maâlem mahjoub', 'eliane azoulay', 'lire le tourbillon des génies', 'bertrand hell', 'ed', 'flammarion', 'cd', 'emi', 'cd sound of world-harmonia mundi']",
 '["cali - l\'amour parfait", \'carte du tendre à coups de chalumeau\', \'amour parfait\', \'tout va bien - cette dernière chanson\', \'anne-marie paquotte\', \'cd labels\', \'les nuits botanique\', \'philippe-auguste\', \'emb\', \'festival primeurs\']',
 '[\'charles levens\', \'jean-philippe rameau\', \'centre de musique baroque de versailles\', \'requiem\', \'ensemble sagittarius\', \'xviie\', \'bordelais\', \'montesquieu\', \'charles levens\', \'ensemble sagittarius\', \'arts florissants\', \'william christie\', \'michel laplénie\', \'charles levens\', \'gilles macassar\', \'charles levens\', \'ensemble sagittarius\', \'michel laplénie\', "cd lira d\'arco", \'codaex france\']',
 "['guided by voices - earthquake glue', 'pavement', 'sonic youth', 'rem', 'guided by voices', 'robert pollard', 'kim deal', 'earthquake glue', 'bee thousand', 'alien lanes', 'david angevin', 'cd beggars/capitol']",
 "['lizz wright - salt', 'lizz wright', 'voix inoubliable', 'tommy lipuma', 'tutu', 'miles davis', 'diana krall', 'verve', 'norah jones', 'blue note', 'saluons', 'lizz wright', 'brian blade', 'roberta flack', 'michel contat', 'cd verve', 'universal']",
 "['anne-marie paquotte', 'cd sterne', 'sony', 'fff']",
 "['nolwenn', 'rafraîchissants', 'maurane', 'anne-marie paquotte', 'cd', 'music']",
 "['lo cor de la plana - es lo', 'le coeur de la plaine', 'manu théron', 'eliane azoulay', 'cd partatge-nocturne', 'fff']",
 "['carlinhos brown - carlito marron', 'mônica passos', 'cd arion', 'cd saravah', 'night & day', 'anne-marie paquotte', 'cd', 'ariola', 'bmg', 'fff']",
 "['kadri gopalnath - scintillating sax', 'adolphe sax', 'eliane azoulay', 'cd dunya', 'fff']",
 '["premier livre d\'orgue", \'olivier vernet\', \'nicolas de grigny\', \'olivier vernet\', \'ligia digital\', \'nicolas de grigny\', \'schubert\', \'nicolas de grigny\', "premier et unique livre d\'orgue", \'jean-sébastien bach\', \'messe\', \'hymnes\', \'veni creator\', \'pentecôte\', \'pange lingua pour la fête-dieu\', \'récit\', \'pange lingua\', \'eucharistie\', \'olivier messiaen\', \'olivier vernet\', \'ensemble\', \'jacques moderne\', \'bernard aubertin\', \'nicolas de grigny\', \'olivier vernet\', \'bossuet\', \'pascal\', \'simon vouet\', \'charles le brun\', \'gilles macassar\', "premier livre d\'orgue", \'nicolas de grigny\', \'olivier vernet\', \'ensemble\', \'jacques moderne\', \'jean-yves hameline\', \'cd\', \'ligia digital\', \'harmonia mundi\']',
 "['ahmad jamal - in search of', 'conseil', 'ahmad jamal', 'should i', 'michel contat', 'dreyfus', 'sony']",
 "['zen zila - 2 pull-overs', 'wahid', 'laurent', 'ulysse', 'voltaire', 'anne-marie paquotte', 'cd az', 'fff']",
 "['miro', 'anne-marie paquotte', 'cd inca', 'emi']",
 '[\'festival\', \'ali farka touré\', \'festival\', \'takamba super onze\', \'sedoum\', \'aïda\', \'philippe brix\', \'bastien gsell\', \'rené gaudin\', \'robert plant\', \'led zeppelin\', "lo\'jo", \'ali farka touré\', \'oumou sangaré\', \'eliane azoulay\', \'cd\', \'music-emi\']',
 "['melting', 'crammed', 'karl biscuit', 'minimal compact', 'tuxedomoon', 'aksak maboul', 'actuel', 'télérama', 'marc hollander', 'crammed discs', 'zappa', 'aksak maboul', 'les tueurs de la lune', 'nationale 7 de trenet', 'zazou-bikaye', 'colin newman', 'wire', 'bel canto', 'crammed discs', 'tuxedomoon', 'bo', 'crammed', 'philippe barbot \\n douze albums', 'colin newman', 'commercial suicide', 'zazou-bikaye', 'noir', 'bel canto', 'white-out conditions', 'les tueurs de la lune de miel', 'honeymoon killers', 'tuxedomoon', 'desire', 'minimal compact', 'deadly weapons', 'elektrowave', 'world fusion', 'internet']",
 "['bordelais', 'eliane azoulay', 'cd paratge-nocturne', 'fff']",
 "['antoine hervé - inside', 'nadia boulanger', 'antoine hervé', 'orchestre national de jazz', 'hervé', 'bravissimo', 'michel contat', 'cd nocturne']",
 "['colin young', 'cd', 'on the beach', 'neil young', 'colin young', 'neil young', 'neil young', 'laurent rigoulet', 'cd', 'reprise records']",
 "['intercontinentals - intercontinentals', 'bill frisell', 'bill frisell', 'vinicius cantuaria', 'warner']",
 "['raphaël - la réalité', 'sur la route, grande chanson', 'gérard manset', 'aubert', 'emi']",
 "['michael franti and spearhead - everyone deserves music', 'boowax', 'labels']",
 "['daniel lanois - shine', 'bono', 'u2', 'pias']",
 "['paddy mcaloon - i trawl the megahertz', 'prefab sprout', 'i trawl the megahertz', 'michael nyman', 'emi']",
 '["artistry of elly ameling  coffrets d\'été", \'elly ameling\', \'pâtre sur le rocher\', \'schubert\', \'bach\', \'haendel\', \'mozart k.\', \'schumann\', \'brahms\', \'wolf\', \'cd philips\', \'fff\']',
 "['jean-sébastien bach - le clavier', 'saluons', 'rosalyn tureck', 'clavier bien tempéré et les', 'variations goldberg - glenn gould', 'bach', 'gould', 'cd bbc legends - distr', 'abeille musique']",
 "['beethoven - les cinq concertos', 'pierre-laurent aimard', 'ligeti', 'boulez', 'nikolaus harnoncourt', 'beethoven', 'cd teldec classics']",
 "['compay segundo', 'compay segundo', 'compay segundo', 'night and day', 'antologia', 'cien años', 'chan chan', 'el commandante che guevara', 'duets', 'aznavour', 'khaled', 'saludo', 'fff', 'compère', 'eliane azoulay']",
 '[\'eminem\', \'white stripes\', \'dwele\', \'ultracool\', \'marvin gaye\', \'dwele\', \'k7\', \'mezza voce\', "d\'angelo", \'marvin gaye\', \'laurent rigoulet\', \'cd virgin\']',
 "['weepers circus - faites', 'inspiré de malicorne', 'têtes raides', 'alexandre george', 'cd carpe diem', 'philips', 'fff']",
 "['jugala - gamelan degung', 'java', 'flûte suling', 'jugala', 'euis komariah', 'gugum gumbira', 'ida widawati', 'eliane azoulay', 'cd pan records', 'abeille musique']",
 "['lio & prévert - coeur de rubis', 'portugaise', 'a.-m.p.', 'cd beluga', 'fff']",
 '[\'paul personne - demain\', "personne, c\'est quelqu\'un : de bien, de fiable", \'paul\', \'johnny\', \'le diable en hiver\', \'partir\', "j\'me taille", \'saoule\', \'en douceur\', "essayer d\'y croire", \'demain\', "les p\'tites routes", \'paul personne\', \'bashung\', "vertige de l\'amour", \'ph\', \'cd polydor\']',
 "['steely dan - everything must go', 'becker', 'fagen', 'bo', 'cd wea', 'fff']",
 '[\'léo\', \'rééditions\', \'léo ferré\', \'léo\', \'noir désir\', \'eiffel\', \'zebda\', \'les hurleurs\', \'léo\', \'bell oeil\', \'léo\', \'oubliés pagny troussant\', \'jolie môme\', \'barbelivien\', "l\'affiche rouge", \'lavilliers\', \'philippe léotard\', \'michel hermon\', \'robert belleret -\', \'léo ferré\', \'ferré\', \'barclay\', \'edith piaf\', \'puni\', \'léo\', \'puni\', \'léo\', \'léo\', \'lionel bourg\', \'la faute\', \'ferré\', \'léo\', \'anne-marie paquotte \\n disques\', \'léo\', \'ferré\', \'barclay\', \'léo\', \'barclay\', \'bell oeil\', \'hurle tout\', \'sony music\', \'manu lann huel chante léo ferré\', "l\'oz productions", \'josette kalifa\', \'david venitucci\', \'chansons de\', \'léo ferré\', \'le loup du faubourg\', \'mélodie\', \'léo ferré\', "une vie d\'artiste", \'robert belleret\', \'faute\', \'ferré\', \'lionel bourg\', \'léo ferré\', \'louis-jean calvet\', \'flammarion\', \'poésie 1 vagabondages no 34\', \'ferré\', \'mémoire et la mer\', \'léo\', \'charles szymkowicz\', \'mémoire et la mer\', \'léo\', \'thank you ferré\', \'ferré\', \'festival des francofolies de la rochelle\']',
 "['chants du moyen atlas', 'berbères', 'moyen atlas', 'chioukh', 'majestueuses', 'tamawayt', 'hassan jouad', 'mohamed rouicha', 'eliane azoulay', 'cd institut du monde arabe', 'harmonia mundi']",
 '[\'gainsbourg\', \'serge gainsbourg\', \'mauvaises nouvelles des étoiles\', \'gainsbourg\', "l\'homme à tête de chou", \'marilou reggae\', \'mauvaises nouvelles des étoiles\', \'sly dunbar\', \'robbie shakespeare\', \'bob marley\', \'i-three\', \'serge\', \'gainsbarre\', \'ecce homo\', \'aux armes\', \'bruno blum\', \'jamaïquains\', \'lone ranger\', \'pas long feu\', \'lisa dainjah\', \'lola\', \'mickey maousse\', \'stéphane jarno\', \'mauvaises nouvelles des étoiles\', \'cd mercury\', \'universal\', \'fff\']',
 "['shirley horn - may', 'quincy jones', 'shirley horn', 'miles davis', 'you wont forget', 'may the music never end', 'if you go away', 'brel', 'nina simone', 'michel contat', 'cd verve', 'universal']",
 "['robert schumann - quintette', 'michelangelo piano quartet', 'quatuor pour piano et cordes', 'robert schumann', 'clara wieck', 'felix mendelssohn', 'orchestre du gewandhaus', 'schumann', 'quintette', 'quatuor -', 'quatuor et ce quintette', 'michelangelo quartet', 'schumann', 'gilles macassar', 'cd chaconne-chandos early', 'codaex d france']",
 "['grandaddy', 'gram parsons', 'neil young', 'jason lytle', 'brian wilson', 'mercury rev', 'loner', 'grandaddy', 'the software slump', 'my heart belongs to grandaddy', 'philippe barbot', 'cd v2']",
 "['stephan eicher - taxi europa', 'louanges', 'herbert grönemeyer', 'max gazzé', 'eicher', 'pierre jaconelli', 'zazie', 'johnny', 'benjamin biolay', 'micheline dax', 'avec toi', 'swim to america', 'cd virgin']",
 "['ismaël lô', 'cd next music', 'fff']",
 "['dejohnette - up for it', 'live in juan-les-pins', 'july 2002', 'standards', 'cd ecm', 'universal', 'fff', 'juan-les-pins jazz festival']",
 "['kindred - surrender to love', 'kindred', 'womack and womack', 'cd epic']",
 "['e.', 'cd dreamworks', 'universal', 'fff']",
 "['dianne reeves - a little moonlight', 'dianne reeves', 'billie holiday', 'grande dianne', 'sarah', 'billie', 'the calling', 'sarah vaughan', 'george duke', 'reeves', 'peter martin', 'reuben rogers', 'gregory hutchinson', 'romero lubambo', 'nicholas payton', 'you go to my head', 'cd blue note', 'emi', 'paris jazz festival']",
 "['the sabri brothers - tasleem', 'nusrat fateh ali khan', 'sabri brothers', 'ghulam farid sabri', 'maqbool ahmed', 'ali khan', 'allah', 'pavarotti', 'ghulam farid', 'eliane azoulay', 'cd pan/abeille musique']",
 "['the postal service - give up', 'sub pop', 'nirvana', 'ben gibbard', 'the district sleeps tonight', 'such great heights', 'belle and sebastian', 'field mice', 'pet shop boys', 'prefab sprout', 'paddy mcaloon', 'emmanuel tellier', 'cd sub pop']",
 "['miles davis - in', 'friday night and saturday night at the blackhawk', 'complete', 'miles', 'blackhawk de san francisco', 'columbia', 'miles', 'john coltrane', 'wynton kelly', 'paul chambers', 'jimmy cobb', 'miles', 'hancock', 'carter', 'williams', 'miles davis the complete live at the plugged nickel', 'blackhawk - deux tiers de musique', 'miles', 'michel contat', 'sony']",
 '[\'hector berlioz\', \'roméo\', "juliette, nuits d\'été - melanie diener", \'kenneth tarver\', \'denis sedov\', \'the cleveland orchestra and chorus\', \'pierre boulez\', \'roméo\', \'pierre boulez\', \'hector berlioz\', \'le lamento\', \'le spectre de la rose\', "nuits d\'été", \'pierre boulez\', \'ninon vallin\', "nuits d\'été !", \'roméo\', \'juliette\', \'orchestre de cleveland\', \'colin davis\', \'philips\', \'john eliot gardiner\', \'hector\', \'attila\', \'gilles macassar \\n coffret\', \'cd deutsche grammophon - enreg\']',
 "['buddy guy - blues singer', 'buddy guy', 'john lee hooker', 'compère mec', 'sweet tea', 'guy', 'santana', 'clapton', 'b.b. king', 'muddy waters', 'junior wells', 'buddy', 'son house', 'johnny shines', 'smokey hogg', 'frankie lee sims', 'philippe barbot', 'cd', 'jive']",
 "['berlioz - symphonie', 'herminie', 'attila', 'scène aux champs', 'huns', 'mahler chamber orchestra', 'hector', 'mahler chamber orchestra', 'marc minkowski', 'cd dg']",
 "['didier squiban - ballades', 'nav', 'anne-marie paquotte', 'cd', 'oz production/coop breizh']",
 "['bastien lallemant - les premiers instants', 'brassens', 'rezvani', 'cd', 'fff']",
 "['led zeppelin', 'how the west was won', 'led zep', 'led zeppelin', 'page', 'plant', 'john bonham', 'zeppelin', 'cd', 'knebworth', 'the song remains the same', 'robert plant', 'jimmy page', 'john paul jones', 'john bonham', 'tous en scène', 'philippe barbot', 'led zeppelin', 'how the west was won', 'cd', 'led zeppelin', 'atlantic-warner']",
 "['the bad plus - these are the vistas', 'bill evans', 'brad mehldau', 'erroll garner', 'jacky terrasson', 'hampton hawes', 'esbjörn svensson', 'bad plus', 'nirvana', 'smells like teen spirit', 'blondie', 'heart of glass', 'aphex twin', 'flim', 'james brown', 'michel contat \\n 1cd columbia', 'sony']",
 "['fabulous trobadors - duels', 'diou biban', 'les fabulous trobadors', 'claude sicre', 'angel b', 'fabulous', 'occitan', 'portuguès', 'anne-marie paquotte', 'cd']",
 '[\'malher\', \'première symphonie\', \'neuvième\', \'gustav mahler\', \'première\', \'pastorale\', \'beethoven\', \'fantastique\', \'berlioz\', \'jean paul\', \'titan\', \'frère jacques\', \'neuvième\', \'grec\', \'dimitri mitropoulos\', \'mariss jansons\', \'mavrinsky\', \'riccardo chailly\', "concertgebouw d\'amsterdam", \'mahler\', \'dixième symphonie\', "orchestre philharmonique d\'oslo", \'gilles macassar\', \'gustav mahler\', \'neuvième symphonies\', \'oslo philharmonic orchestra\', \'mariss jansons\', \'cd simax classics\', \'intégral\', \'bruckner\', \'mahler\', \'strauss\', \'vienna philharmonic\', \'karajan\', \'mitropoulos\', \'böhm\', \'cd andante\']',
 "['créole band', 'world music', 'seconde guerre mondiale', 'la coupole', 'filiberto rico', 'oscar lopez', 'filiberto rico', 'eliane azoulay', 'cd frémeaux & associés', 'night and day']",
 "['the dandy warhols - welcome to the monkey house', 'thirteen tales from urban bohemia', 'ride', 'my bloody valentine', 'velvet underground', 'andy warhol', 'courtney taylor', 'nick rhodes', 'duran duran', 'welcome to the monkey house', 'nick rhodes', 'simon le bon', 'plan a', 'courtney taylor', 'we used to be friends', 'you were the last high', 'dandy warhols', 'david angevin', 'emi']",

In [ ]:
for row in press["name"]:
    for name in row:
        if name not in french_stopwords:
            name
        else:

stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword
stopword

KeyboardInterrupt: