In [ ]:
from tqdm import tqdm
import pandas as pd
import spacy
import re
import unicodedata
from unidecode import unidecode
import ast
from collections import Counter

In [2]:
pd.set_option('display.max_columns', 30)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [3]:
ents = pd.read_csv("/Users/pol/Downloads/extracted_ents_ALL.csv", sep=';')
ents = ents.dropna(subset=["name"])
ents

press = pd.read_csv("/Users/pol/Downloads/agg_matches_ALL.csv", sep=';')
press

,article_id,article_text,name,name_count
0,1,Serge Reggiani - Succès & confidences .\n Une ...,"['Serge Reggiani - Succès & confidences', 'Reg...",1
1,2,"Désolés, Warren .\n C'est une maigre consolati...","['Warren', 'Warren Zevon', ""I'll sleep when I'...",10
2,3,Adam Green - Friends of mine .\n Dire qu'on a ...,"['Adam Green - Friends of mine', 'The Kills', ...",1
3,4,Cesaria Evora - Voz d'amor .\n Dès les premièr...,"['gorgée', 'Voz', ""Voix de l'amour"", 'Velocida...",2
4,5,Herman Düne - Mas cambios et Mash Concrete Met...,"['Herman Düne - Mas cambios', 'Mash Concrete M...",1
...,...,...,...,...
52639,52690,"Rap, jazz, rock, classique, chanson… Les album...","['Rap', 'Monde', 'An Evening with Silk Sonic',...",45
52640,52691,Que sait-on vraiment des surrisques de contami...,"['Covid-19', 'Omicron', 'Jean Castex', 'Covid-...",482
52641,52692,"Rencontre avec Riccardo Muti, maestro à vie .\...","['Riccardo Muti', 'Riccardo Muti', 'Cristina',...",70
52642,52693,Ils sont passés chez Colors : la sélection mus...,"['Colors', 'Monde Afrique', 'Le Monde Afrique'...",27
52643,52694,Musique : des enregistrements historiques venu...,"['Pierre-Emmanuel Barbier', 'Thomson', 'Diapas...",1

### check texts with possible false positives

In [99]:
count = 0

for i, (text, namelist) in enumerate(
    zip(press["article_text"],
        press["name"]
        )):
    if ("'Johnny Cash'" in namelist and "'Johnny'"):
        #print(i)
        count += 1

print(count)

220

In [44]:
press["name"] = press["name"].apply(ast.literal_eval)
press["name"]

0        [Serge Reggiani - Succès & confidences, Reggia...
1        [Warren, Warren Zevon, I'll sleep when I'm dea...
2        [Adam Green - Friends of mine, The Kills, Gree...
3        [gorgée, Voz, Voix de l'amour, Velocidade, Ces...
4        [Herman Düne - Mas cambios, Mash Concrete Meta...
                               ...
52639    [Rap, Monde, An Evening with Silk Sonic, Silk ...
52640    [Covid-19, Omicron, Jean Castex, Covid-19, Clu...
52641    [Riccardo Muti, Riccardo Muti, Cristina, Ricca...
52642    [Colors, Monde Afrique, Le Monde Afrique, Colo...
52643    [Pierre-Emmanuel Barbier, Thomson, Diapason, P...
Name: name, Length: 52644, dtype: object

In [90]:
def count_name_cooc(target_name, position="first"):
    """
    namelists: iterable of lists of extracted names
    target_name: string (e.g. "christophe" or "mae")
    position: "first" or "last"
    """

    target_name = target_name.lower()
    alone_count = 0
    cooccurrence_counter = Counter()

    for namelist in press["name"]:

        names_lower = [n.lower() for n in namelist]

        # Case 1: FIRST NAME logic
        if position == "first":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.startswith(target_name + " ")]

            if has_alone and not full_names:
                alone_count += 1

            elif has_alone and full_names:
                for full_name in full_names:
                    last_part = full_name[len(target_name)+1:]
                    cooccurrence_counter[last_part] += 1

        # Case 2: LAST NAME logic
        elif position == "last":
            has_alone = target_name in names_lower
            full_names = [n for n in names_lower if n.endswith(" " + target_name)]

            if has_alone and not full_names:
                alone_count += 1

            elif has_alone and full_names:
                for full_name in full_names:
                    first_part = full_name[:-(len(target_name)+1)]
                    cooccurrence_counter[first_part] += 1

        else:
            raise ValueError("position must be 'first' or 'last'")

    return alone_count, cooccurrence_counter

In [107]:
target_name = "reich"

alone, with_last = count_name_cooc(
    target_name=target_name,
    position="last"
)

print(f"'{target_name}' alone:", alone, "\n")
print(f"'{target_name}' with:", "\n")
for k, v in with_last.most_common():
    print(f"'{k}': {v}")

'reich' alone: 44

'reich' with:

'steve': 12
'iiie': 8
'wilhelm': 2
'ive': 2
'maître forestier du': 1
'iie': 1

In [71]:
n = 10                       
count = 0
artist = "Rolling"

for i, (text, namelist) in enumerate(zip(press["article_text"],
                                         press["name"])):
    if artist in namelist:
        print(i)
        print(namelist)
        print("-------------------")
        print(text)
        print("===================")

        count += 1

print(f"{count} OCCURRENCES OF '{artist}'")

1332
['Kanye West', 'Curtis', 'Rolling', 'Kanye West', 'Muhammad Ali', 'Bush', 'Katrina', 'Daft Punk', 'Coldplay', '50 Cent', 'Mike Tyson', 'Sonny Liston', 'Curtis', 'Laurent Rigoulet', 'CD Barclay', 'CD Polydor']
-------------------
Kanye West. Graduation - 50 Cent. Curtis .
 En couverture du Rolling Stone américain, ils se toisent méchamment comme deux boxeurs à la veille du match du siècle. A gauche, 50 Cent, à droiteKanye West, deux poids lourds du rap US dont les albums sont sortis le même jour de septembre, histoire de créer l'événement et de redonner un peu de muscle à l'industrie du disque moribonde. Même s'ils boxent tous deux dans la catégorie multiplatine, ces deux stars de l'Amérique noire s'appuient sur des styles très différents.
 Kanye West est un genre de Muhammad Ali rap, agile et malin, un baratineur éclairé et engagé (ses fameuses sorties contre Bush après la catas­trophe Katrina), doublé d'un technicien hors pair, dont les arrangements tissent d'habiles variations sur les classiques soul et les standards de la pop moderne. Passant en souplesse de Daft Punk au reggae, des mélodies de Broadway à la voix de Coldplay, son troisième album est une nouvelle réussite, dont la production ingénieuse dévoile lentement les richesses.
En regard, 50 Cent est une terreur du ghetto, un démolisseur pur et dur, façon Mike Tyson ou Sonny Liston, qui rejoue avec un redoutable sang-froid sa prestation de mauvais garçon. Aucune surprise sur Curtis, mais toujours le même savoir-faire, la même morgue jouissive, qui se déploie en majesté sur un rythme lent, infernal, aussi obsédant que les vieux blues qui retournaient les sangs. Belle affiche.
 Laurent Rigoulet

 1 CD Barclay et 1 CD Polydor.
===================
1446
['Patti Smith', 'Lou Reed', 'Phrase terrible', 'Lou Reed', 'Velvet Underground', 'Robert Christgau', 'Rolling', 'Reed', 'Lou Reed', 'Velvet Undergound', 'Lou Reed', 'Reed', 'Velvet', "I'll be your mirror", 'Pale Blue Eyes', 'Lou Reed', 'Velvet', 'Caroline says II', 'Lou Reed', 'Laurie Anderson', 'Reed', 'tai-chi', 'Cary Grant', 'Lou Reed', '- Reed', 'Magic and loss', 'Julian Schnabel', 'Lola', 'Schnabel', 'Hal Willner', 'Bob Ezrin', 'Steve Hunter', 'Lou Reed', 'Reed', 'Susan Feldman', 'Andy Warhol', 'Songs for Drella', 'John Cale', 'Julian Schnabel', 'Bob Ezrin', 'Steve Hunter', 'Lou Reed', 'Transformer', 'fai\xadtes', 'Lou Reed', 'Delmore Schwartz - célébré', 'T.S. Eliot', 'Nabokov', 'Lou Reed', 'Delmore Schwartz', 'Lou Reed', "Deep down inside I've got", 'Air Force', 'The Kids', 'Lou Reed', 'David Bowie', 'Velvet', 'Transformer', 'Walk on the wild side', 'Lou', 'la Factory', 'Andy Warhol', 'toop tootoop tootoop', 'Lou Reed', 'Bowie', 'Lou Reed', 'Bob Ezrin', 'Alice Cooper', 'Transformer', 'Bob', 'Jack Bruce', 'Steve Winwood', 'Aynsley Dunbar', "Moi je me suis contenté d'un peu de guitare acoustique", 'Kurt Weill', 'Bowie', 'T. Rex', 'Transformer', 'Ezrin', 'The Bed', 'Burroughs', 'Selby', 'Antiquité', 'Soprano', 'Ça', 'Lou Reed', 'Caroline', 'Jim', 'Reed', 'Lou', 'Lou Reed', 'Dominer', 'Velvet Underground', 'John Cale', 'Reed', 'Lou Reed', 'Edie Sedgwick', 'Andy Warhol', 'Nico', 'Sterling Morrison', 'Velvet', 'Warhol', 'Warhol', 'Hugo Cassavetti \n \xa0 \n A', 'Lou Reed', 'Festival des Nuits de Fourvière', 'Les Nuits New York', 'Patti Smith', 'Antony and the Johnsons', 'Joan as Police Woman', 'Philip Glass', 'Laurie Anderson', 'CD RCA']
-------------------
Retour à Berlin .
 « Comment un type aussi désagréable peut-il écrire de si magnifiques chansons ? » Patti Smith se fit cette réflexion en 1976, après une visite à Lou Reed. Phrase terrible, qui trotte depuis belle lurette dans la tête de bien des amateurs de l'irascible rocker new-yorkais. Monument intimidant de 65 ans, Lou Reed (une trentaine d'albums au compteur depuis 1967 et le premier disque du Velvet Underground, le groupe le plus mythique de l'histoire du rock) est comme un chien qui s'est fait marcher sur la queue : méfiant, toujours prêt à mordre, il se crispe, se met sur la défensive dès qu'il se trouve en présence d'un journaliste. Les récits de reporters humiliés, séchés par une pique du poète-musicien sont légion. Pourquoi tant de mépris à l'égard de ceux qui l'admirent, vivent avec et parfois même par ses chansons ?
On peut sans doute faire porter le chapeau à Robert Christgau. Ce critique au tout-puissant magazine Rolling Stone se fendit, en 1973, d'une chronique littéralement assassine de Berlin, l'ambitieux album tout juste publié par Reed. « Cet album sinistre, musicalement mé­dio­cre, est une offense. Il faudrait pou­voir se venger d'un tel disque, s'en prendre même physiquement à son auteur », écrivait-il en substance. Lou Reed, plus à l'aise dans le rôle de celui qui distribue les coups, en fut profondément meurtri. Ce rejet (l'album fut un échec commercial) de ce qu'il considérait comme son oeuvre la plus personnelle et aboutie jusque-là le fera sombrer dans le dépit, la rancoeur, le cynisme. Un fossé d'incompréhension allait se creuser entre un artiste toujours performant mais un homme public distant, mal embouché, et un public condamné à contempler une caricature.
 « Le Velvet Undergound, ce n'était pas le côté obscur du rock'n'roll, mais le côté lumineux. » Il y a bien longtemps, Lou Reed avait ainsi défini la musique de son groupe (1964-1970), commercialement inexistant mais déclencheur de mille vocations, à jamais associé à la face sombre, dépressive et morbide du rock. Pourtant, les textes de Reed, dès l'époque du Velvet, outre leur qualité littéraire revendiquée et avérée, n'offraient ni fantasmes bon marché ni enfilades de clichés : plutôt des tranches de vie, des portions d'existences extrêmes, radicales, désespérées. De la chanson vérité, en quelque sorte. Au détour de ses récits dépeignant la faune marginale du New York des sixties se nichaient également de somptueuses chansons d'amour, parmi les plus belles jamais écrites (I'll be your mirror, Pale Blue Eyes...). Et, en 1973, Berlin, le disque-concept de Lou Reed en solo, racontait la des­cente aux enfers d'un couple d'amants perdus, incapables de s'aimer, de s'aider, de communiquer : il connut à peu près le même sort que les albums du Velvet. L'histoire, tel un cauchemar, se répétait.

 « Caroline dit, en se relevant du sol / Pourquoi me frappes-tu ? / Ce n'est pas drôle.
 Caroline dit, en maquillant son oeil tuméfié / tu devrais apprendre à te connaître un peu mieux / à penser à autre chose que toi... » Caroline says II (septième chanson de l'album Berlin, en 1973)

 En cette fin d'après-midi de mai 2007, Lou Reed donne rendez-vous dans un restaurant italien chic du quartier de Chelsea, à Manhattan. Son humeur bascule entre la joie de bien manger avant d'aller voir un concert de sa bien-aimée Laurie Anderson et la douleur d'avoir à se confronter à des questions sur sa carrière. Plus intello new-yorkais que jamais avec ses lunettes design, sa voix ferme mais douce, son vocabulaire précis et son débit mesuré, Reed a le corps sec et nerveux d'un homme qui s'adonne trois heures par jour au tai-chi (il vient même de sortir un disque new age de musique méditative). Par réflexe, il cherche à déstabiliser son interlocuteur (« Posez des questions claires », « Je ne suis pas une machine à débiter des réponses », « Vous n'êtes pas venu que pour moi à New York ? », « On s'est déjà rencontrés ? Et vous êtes toujours en vie ? »). Mais plus qu'hostile on le sent craintif, rétif à l'analyse, prompt à détecter l'attaque là où elle n'est pas. Bref, un type qui préfère de loin les digressions sur le talent d'acteur de Cary Grant à l'explication de texte de ses propres chansons.
 Lou Reed a pourtant de quoi être réjoui. Berlin, son album maudit, revit. Après deux représentations exceptionnelles à New York (puis à Sydney) l'hiver dernier, il a consenti à réitérer l'expérience en Europe. Non pas pour se plier à la dernière mode (rejouer un album dans l'ordre et dans son intégralité - Reed, en précurseur, l'a déjà fait avec Magic and loss en 1992), mais pour réparer une injustice, prendre une revanche, aller au bout d'une aventure inachevée. Le concert, donné au St. Ann's Warehouse de Brooklyn, fut un triomphe artistique. Avec Julian Schnabel à la mise en scène, un film de Lola (la fille) Schnabel projeté en fond, Hal Willner et Bob Ezrin à la direction artistique, le vétéran Steve Hunter à la guitare ou le phénomène Antony aux choeurs, et Lou Reed, magique, en voix, resplendissant à la six-cordes... Six mois après, grâce au travail de persuasion de quelques Européens acharnés (le festival lyonnais de Fourvière, notamment), Berlin, l'oeuvre majeure de Reed, arrive dans nos contrées.
 « Mon amie Susan Feldman, déjà à l'origine du spectacle en hommage à Andy Warhol, Songs for Drella, avec John Cale, en 1990, me harcelait depuis quinze ans pour que je re­joue Berlin. Puis Julian Schnabel m'a dit qu'il fallait absolument en tirer un film. Ensuite, Bob Ezrin, le producteur du disque original, et Steve Hunter, le guitariste, s'y sont mis... Je me suis dit : pourquoi pas ? » Entre-temps, Lou Reed a aussi découvert le statut de classique que son Berlin mal-aimé a acquis au cours des ans. Avec Transformer (1972), c'est son album qui se vend le plus régulièrement.
 « J'ai toujours pensé qu'il fallait considérer les disques comme des romans ou des films, c'est-à-dire comme des oeuvres cohérentes, fai­tes pour être écoutées dans un ordre précis. Pas juste un recueil de chansons plus ou moins entraînantes ou jolies. » Cette vision ambitieuse du rock, Lou Reed la tient de son mentor et modèle, le brillant mais autodestructeur poète Delmore Schwartz - célébré par T.S. Eliot et Nabokov -, dont il a suivi assidûment les cours d'écriture à la fac, jus­qu'à devenir son protégé. Lou Reed l'a vu mourir trop tôt, misérable, ignoré. Delmore Schwartz dédaignait le rock. C'est pour lui que Lou Reed s'est juré de faire du beat primaire qui rythme depuis toujours le battement de son coeur (« Deep down inside I've got a rock'n'roll heart ») le support d'une musique adulte.

 « Ils lui retirent ses enfants / Parce qu'ils disent que c'est une mauvaise mère / A cause de tout ce qu'on a raconté sur elle / l'officier noir de l'Air Force et tous ceux qui l'ont précédé / Et puis toutes les drogues qu'elle s'est injectées... » The Kids (huitième chanson de Berlin)

 En 1972, Lou Reed, rocker culte mais confidentiel, est propulsé vedette du « glam rock » grâce à David Bowie, fan du Velvet, instigateur et producteur de Transformer. Son unique tube, Walk on the wild side et son swing délicat, description sans fard de tous les paumés que Lou a côtoyés à la Factory d'Andy Warhol, est sur toutes les lèvres. La chanson parle de travestis, de transsexuels, de gitons, de junkies, évoque même la fellation, mais le grand public et les radios n'entendent que les irrésistibles « toop tootoop tootoop... » fredonnés par le choeur des prostituées. Lou Reed, teint blafard, fardé comme un acteur du muet, est donc enfin une star. Mais son ego supporte mal la sensation d'avoir été manipulé, dépossédé, exploité par son sauveur Bowie. Après un album qu'il juge « compromis », Lou Reed se dit que le monde est prêt pour lui. Mais lui seul.
 Bob Ezrin, jeune producteur à succès du sulfureux Alice Cooper, a déclenché le processus d'écriture de Berlin, successeur attendu de Transformer. « Bob adorait la chanson Berlin, cette histoire de couple, dans un café, se rappelant de doux moments passés. Il voulait en connaître la suite. Voilà comment c'est parti. J'ai écrit les chansons en quelques jours puis il les a prises, les a arrangées. Un vrai travail de producteur. A Londres, il a recruté les plus grands musiciens de l'époque, Jack Bruce, Steve Winwood, Aynsley Dunbar, concocté de prodigieux arrangements... Moi je me suis contenté d'un peu de guitare acoustique pour me concentrer sur ma voix. »
 Le résultat, majestueusement glauque, tient plus de l'intensité d'un Kurt Weill que de la joyeuse décadence de façade du glam. On est loin du rock pétillant et sensuel de Bowie ou de T. Rex. Et surtout de la savoureuse malice de Transformer. Berlin, entre cabaret poisseux et rock baroque, est une poignante symphonie du malaise et du mal-être. Autant dire qu'il fiche le bourdon. Trop dur, trop noir, trop malsain. Pas glamour pour un sou, l'oeu­vre devint un objet de vénération pour initiés. « A l'époque, on devait monter une tournée théâtrale avec de gros moyens. Mais à cause de l'accueil glacial du disque, ça n'a jamais abouti. Ezrin a récemment ressorti le projet : les plans, les sketchs, les essais de décors - l'hôtel, la boîte sordide... Il avait tout gardé. »

 « Voici l'endroit où elle reposait sa tête / le soir lorsqu'elle se couchait.
 Voici l'endroit où ses enfants ont été conçus / cette chambre éclairée aux chandelles.
 Et voici l'endroit où elle s'est ouvert les veines / cette étrange et fatale nuit. » The Bed (neuvième chanson de Berlin)

 « Dans un monde d'écrivains brillants comme Burroughs ou Selby, pourquoi un relativement inoffensif disque de rock comme Berlin a-t-il été à ce point vilipendé, rejeté ? Parce que l'émotion produite par la musique est dévastatrice. Ce n'est pas le livret, il tient en trois phrases : homme trouve fille, homme perd fille, fille ne revient pas dans la scène finale. Berlin parle avant tout de la jalousie. Un sentiment plutôt éternel, non ? Je ne connais pas un être vivant qui n'a pas été maladivement jaloux. C'est un thème universel, depuis l'Antiquité grecque jusqu'aux Soprano... La liste de grands livres dix fois plus sombres et déprimants que Berlin est interminable. Ça confirme ma conviction que la musique frappe plus fort les esprits, touche plus profond que n'importe quel autre art. »
 Si Berlin n'a rien d'une autobiographie, on y décèle un lourd parfum de vécu. L'incommunicabilité, Lou Reed connaît. L'amour destructeur, la violence, la mort, le rejet également. Tout comme ses antihéros, Caroline et Jim, Reed vient d'un bon milieu, et il s'est heurté à l'incompréhension de ses parents.
 En 1959, inquiets devant la tournure trouble que prend la sexualité de leur fils et de la passion qu'il s'est découverte pour le rock'n'roll, ses parents n'hésitent pas à lui faire subir des séances d'électrochocs. C'était la mode, à l'époque. Lou avait 17 ans. Il en a développé une forme de paranoïa aiguë - à qui faire confiance ? - et une accoutumance aux médicaments. Une porte ouverte à la toxicomanie, à une vision déformée de l'amour. Depuis, Lou Reed s'est toujours construit dans la réaction, les rapports de force. Dominer l'autre pour ne pas subir sa loi. Voilà la recette du style unique et révolutionnaire du Velvet Underground, fruit d'une rivalité créative entre John Cale et Reed. Et la raison de son inévitable implosion prématurée...
 Lou Reed, l'incarnation de la mauvaise vie, de l'excès, de l'autodestruction, a survécu à la plupart de ses contemporains, Edie Sedgwick, Andy Warhol, Nico, Sterling Morrison (le guitariste du Velvet)... Par quel miracle ? « Ce n'est pas en faisant le malin, croyez-moi. Un bon ré­gime, de l'exercice quotidien. Et puis beaucoup de chance. Aucun homme n'a trop de chance... Et puis, vous savez, je viens de l'école Warhol. Je n'ai donc pas le moindre souci avec ce qu'on peut dire de moi ou de mon oeuvre : les mêmes gens ont traîné Warhol dans la boue avant de le cé­lébrer, après coup, comme l'un des plus grands artistes du XXe siècle. Bien sûr, les mauvaises critiques font mal dans le sens où elles vous empêchent parfois de réaliser des envies, des rêves. Comme monter Berlin en spectacle en 1973. Mais je n'ai jamais douté de la qualité du disque. Je n'ai pas besoin qu'on vienne me dire que ce que je fais est bon. Je le sais. » .
 Hugo Cassavetti

 A voir
 Berlin, de Lou Reed, le 23 juin au Palais des congrès, Paris; le 4 juillet au Théâtre antique d'Arles.
 Festival des Nuits de Fourvière. Dans le cadre de ce festival, le 3 juillet aux Théâtres romains de Fourvière, Lyon, représentation précédée d'une semaine de programmation exceptionnelle baptisée « Les Nuits New York », avec Patti Smith (le 29 juin), Antony and the Johnsons et Joan as Police Woman (le 30), Philip Glass (le 1er juillet) et Laurie Anderson (le 2).

 A écouter
 Berlin, 1 CD RCA.
===================
2477
['Ron Wood', 'Stone', 'Ronnie Wood', 'K&B', 'Rolling', 'Leaving Here', 'The Birds', 'Wood', 'Yardbirds', 'Kinks', 'Eddie Holland', 'Who', 'Motörhead', 'Single', 'Decca', 'Rock My Plimsoul', 'Jeff Beck Group', 'Jeff Beck', 'Wood', 'Rod Stewart', 'Album  Truth', 'Columbia', 'The Faces', 'Faces', 'Rod Stewart', 'Ron', 'Album  Ooh', 'Warner', 'Hey Negrita', 'The Rolling Stones', 'Ronnie Wood', 'squeezer', 'Keith Richards', 'Album  Black and blue', 'EMI', 'Seven Days', 'Ronnie Wood', 'Ron Wood', 'Bob Dylan', 'Ron', 'Zim', 'Album  Gimme some neck', 'Hugo Cassavetti \n \xa0 \n A']
-------------------
Ron Wood, pas seulement Stone .
 L'autobiographie de Ronnie Wood qui vient de paraître en traduction française (K&B éditions) n'a rien du chef-d'oeuvre, mais offre un vrai plaisir de lecture. Pouvait-il en être autrement de la part du Rolling Stone le plus sympathique, guitariste facétieux qui conjugue depuis quarante-cinq ans passion rock et bonne humeur, au point d'être devenu l'ami et le confident de tous ?

 Leaving Here. The Birds (1965)
Premier single du jeune Wood avec son groupe beat, dans la pure lignée des Yardbirds et des Kinks. Une solide cover enjouée d'un standard d'Eddie Holland que reprendront aussi les Who et Motörhead.
Single  Decca.

 Rock My Plimsoul. Jeff Beck Group (1968)
Pour jouer avec le grand Jeff Beck, qui ne supportait pas la compète, Wood accepte de se mettre à la basse. La naissance d'un certain hard rock et le début d'une longue histoire avec Rod Stewart.
 Album  Truth,  Columbia.

 Ooh la La. The Faces (1973)
Sur l'ultime album des Faces, au bord de la désintégration, Rod Stewart refusait de chanter cette chanson « idiote ». Ron s'en chargea donc. Avec les honneurs.
 Album  Ooh la la,  Warner.

 Hey Negrita. The Rolling Stones (1976)
Guère plus qu'une torride jam funky, mais une jam qui valut à Ronnie Wood de squeezer définitivement ses concurrents pour la place vacante de frère de riffs de Keith Richards.
 Album  Black and blue,  EMI.

 Seven Days. Ronnie Wood (1979)
Tout le monde aimait Ron Wood, même Bob Dylan, fan du premier brinquebalant album solo du guitariste jovial. Du coup, il lui offrit ce chouette morceau sur lequel Ron imitait le Zim à la perfection.
 Album  Gimme some neck,  Columbia.
 Hugo Cassavetti

 A écouter sur telerama.fr/musique
===================
4213
['People', 'Hell and Angels Jimi Hendrix', 'Jimi Hendrix', 'Net', 'Hendrix', 'People', 'Hell and Angels', 'Black Gold', 'Janie Hendrix', 'Toile', 'Stephen Stills', 'Lonnie Youngblood', 'John McDermott', 'Eddie Kramer', 'Hendrix', 'Earth Blues', 'People', 'Hell and Angels', 'Hendrix', 'Billy Cox', 'Buddy Miles', 'Wilson Pickett', 'Band of Gypsys', 'Hendrix', 'Electric Ladyland', 'Fillmore East', 'Hendrix', 'Egaré', 'Rolling', 'Baby let me move you', 'Mojo Man', 'Easy Blues', 'Hendrix', 'Swinging London', 'Dylan', 'Blancs', 'Black Power', 'Band of Gypsys', 'Hendrix', 'Voodoo Chile', 'Black Panthers', 'Hendrix', 'Ike Turner', 'People', 'Hell and Angels', 'Hendrix', 'Miles Davis', 'Stevie Wonder', 'George Clinton', 'Frank Zappa', 'Laurent Rigoulet \n People', 'hell and angels', 'CD Legacy', 'Sony', 'Compilation Télérama', 'CD', 'Télérama', 'Télérama.fr']
-------------------
People, Hell and Angels Jimi Hendrix .

In [69]:
n = 10                       
count = 0
artist = "Rolling"

for i, (text, namelist) in enumerate(zip(press["article_text"],
                                         press["name"])):
    if artist in namelist:
        # split the article into tokens and look for the artist token(s)
        words = text.split()
        for idx, w in enumerate(words):
            if w.lower() == artist.lower():
                lo = max(0, idx - n)
                hi = idx + n + 1
                snippet = " ".join(words[lo:hi])
                print("------------------------")
                print(i)
                print(namelist)
                print(snippet) # only n words before/after
        count += 1

print("==================")
print(f"{count} OCCURRENCES OF '{artist}'")

------------------------
1332
['Kanye West', 'Curtis', 'Rolling', 'Kanye West', 'Muhammad Ali', 'Bush', 'Katrina', 'Daft Punk', 'Coldplay', '50 Cent', 'Mike Tyson', 'Sonny Liston', 'Curtis', 'Laurent Rigoulet', 'CD Barclay', 'CD Polydor']
West. Graduation - 50 Cent. Curtis . En couverture du Rolling Stone américain, ils se toisent méchamment comme deux boxeurs à
------------------------
1446
['Patti Smith', 'Lou Reed', 'Phrase terrible', 'Lou Reed', 'Velvet Underground', 'Robert Christgau', 'Rolling', 'Reed', 'Lou Reed', 'Velvet Undergound', 'Lou Reed', 'Reed', 'Velvet', "I'll be your mirror", 'Pale Blue Eyes', 'Lou Reed', 'Velvet', 'Caroline says II', 'Lou Reed', 'Laurie Anderson', 'Reed', 'tai-chi', 'Cary Grant', 'Lou Reed', '- Reed', 'Magic and loss', 'Julian Schnabel', 'Lola', 'Schnabel', 'Hal Willner', 'Bob Ezrin', 'Steve Hunter', 'Lou Reed', 'Reed', 'Susan Feldman', 'Andy Warhol', 'Songs for Drella', 'John Cale', 'Julian Schnabel', 'Bob Ezrin', 'Steve Hunter', 'Lou Reed', 'Transformer', 'fai\xadtes', 'Lou Reed', 'Delmore Schwartz - célébré', 'T.S. Eliot', 'Nabokov', 'Lou Reed', 'Delmore Schwartz', 'Lou Reed', "Deep down inside I've got", 'Air Force', 'The Kids', 'Lou Reed', 'David Bowie', 'Velvet', 'Transformer', 'Walk on the wild side', 'Lou', 'la Factory', 'Andy Warhol', 'toop tootoop tootoop', 'Lou Reed', 'Bowie', 'Lou Reed', 'Bob Ezrin', 'Alice Cooper', 'Transformer', 'Bob', 'Jack Bruce', 'Steve Winwood', 'Aynsley Dunbar', "Moi je me suis contenté d'un peu de guitare acoustique", 'Kurt Weill', 'Bowie', 'T. Rex', 'Transformer', 'Ezrin', 'The Bed', 'Burroughs', 'Selby', 'Antiquité', 'Soprano', 'Ça', 'Lou Reed', 'Caroline', 'Jim', 'Reed', 'Lou', 'Lou Reed', 'Dominer', 'Velvet Underground', 'John Cale', 'Reed', 'Lou Reed', 'Edie Sedgwick', 'Andy Warhol', 'Nico', 'Sterling Morrison', 'Velvet', 'Warhol', 'Warhol', 'Hugo Cassavetti \n \xa0 \n A', 'Lou Reed', 'Festival des Nuits de Fourvière', 'Les Nuits New York', 'Patti Smith', 'Antony and the Johnsons', 'Joan as Police Woman', 'Philip Glass', 'Laurie Anderson', 'CD RCA']
le chapeau à Robert Christgau. Ce critique au tout-puissant magazine Rolling Stone se fendit, en 1973, d'une chronique littéralement assassine de
------------------------
2477
['Ron Wood', 'Stone', 'Ronnie Wood', 'K&B', 'Rolling', 'Leaving Here', 'The Birds', 'Wood', 'Yardbirds', 'Kinks', 'Eddie Holland', 'Who', 'Motörhead', 'Single', 'Decca', 'Rock My Plimsoul', 'Jeff Beck Group', 'Jeff Beck', 'Wood', 'Rod Stewart', 'Album  Truth', 'Columbia', 'The Faces', 'Faces', 'Rod Stewart', 'Ron', 'Album  Ooh', 'Warner', 'Hey Negrita', 'The Rolling Stones', 'Ronnie Wood', 'squeezer', 'Keith Richards', 'Album  Black and blue', 'EMI', 'Seven Days', 'Ronnie Wood', 'Ron Wood', 'Bob Dylan', 'Ron', 'Zim', 'Album  Gimme some neck', 'Hugo Cassavetti \n \xa0 \n A']
de lecture. Pouvait-il en être autrement de la part du Rolling Stone le plus sympathique, guitariste facétieux qui conjugue depuis quarante-cinq
------------------------
2477
['Ron Wood', 'Stone', 'Ronnie Wood', 'K&B', 'Rolling', 'Leaving Here', 'The Birds', 'Wood', 'Yardbirds', 'Kinks', 'Eddie Holland', 'Who', 'Motörhead', 'Single', 'Decca', 'Rock My Plimsoul', 'Jeff Beck Group', 'Jeff Beck', 'Wood', 'Rod Stewart', 'Album  Truth', 'Columbia', 'The Faces', 'Faces', 'Rod Stewart', 'Ron', 'Album  Ooh', 'Warner', 'Hey Negrita', 'The Rolling Stones', 'Ronnie Wood', 'squeezer', 'Keith Richards', 'Album  Black and blue', 'EMI', 'Seven Days', 'Ronnie Wood', 'Ron Wood', 'Bob Dylan', 'Ron', 'Zim', 'Album  Gimme some neck', 'Hugo Cassavetti \n \xa0 \n A']
les honneurs. Album Ooh la la, Warner. Hey Negrita. The Rolling Stones (1976) Guère plus qu'une torride jam funky, mais une
------------------------
4213
['People', 'Hell and Angels Jimi Hendrix', 'Jimi Hendrix', 'Net', 'Hendrix', 'People', 'Hell and Angels', 'Black Gold', 'Janie Hendrix', 'Toile', 'Stephen Stills', 'Lonnie Youngblood', 'John McDermott', 'Eddie Kramer', 'Hendrix', 'Earth Blues', 'People', 'Hell and Angels', 'Hendrix', 'Billy Cox', 'Buddy Miles', 'Wilson Pickett', 'Band of Gypsys', 'Hendrix', 'Electric Ladyland', 'Fillmore East', 'Hendrix', 'Egaré', 'Rolling', 'Baby let me move you', 'Mojo Man', 'Easy Blues', 'Hendrix', 'Swinging London', 'Dylan', 'Blancs', 'Black Power', 'Band of Gypsys', 'Hendrix', 'Voodoo Chile', 'Black Panthers', 'Hendrix', 'Ike Turner', 'People', 'Hell and Angels', 'Hendrix', 'Miles Davis', 'Stevie Wonder', 'George Clinton', 'Frank Zappa', 'Laurent Rigoulet \n People', 'hell and angels', 'CD Legacy', 'Sony', 'Compilation Télérama', 'CD', 'Télérama', 'Télérama.fr']
être un clown » , dit-il à une journaliste de Rolling Stone venue lui rendre visite lors d'une de ces séances
------------------------
4326
['Nó na Orelha Criolo', "Grammy'", 'MTV Brazil', 'Rolling', 'Brazil', 'Caetano Veloso', 'Samba Sambei', 'Subirusdoistiozin', 'MPB', 'Linha', 'Frente', 'SP', 'Sucrilhos', 'Lion Man', 'Wu-Tang', 'Grajauex', 'Anne Berthod', 'CD Sterns', 'Harmonia Mundi']
été sacré plusieurs fois meilleur album 2011 (Grammy's, MTV Brazil, Rolling Stone Brazil ...) à sa sortie au Brésil. Sans aller
------------------------
6897
['Gojira', 'Mario Duplantier', 'Mario', 'Joe', 'Christian Andreu', 'Jean-Michel Labadie', 'Download Festival', 'Hellfest', 'Magma', 'Rolling', 'Gojira', 'Godzilla', 'Joe', 'Mario Duplantier', 'Christian', 'Metallica', 'Mario', 'Jean-Michel', 'Sepultura', 'Slayer', 'Pantera', 'Joe', 'CD', 'Gojira', 'frères Duplantier', "L'Enfant sauvage", 'Mario', 'Joe', 'Sea Shepherd', 'Joe', 'Christian', 'Jean-Michel', 'Gojira', 'Christian', 'Joe', 'Immortal', 'Joe', 'Terra incognita', 'Joe', 'Gojira', 'Kerrang', 'From Mars to Sirius', 'Gojira', 'Mastodon', 'Download Festival', 'Ça', 'Joe', 'Lamb of God', 'Metallica', 'Français', 'Christian', 'Metallica', 'Joe', 'Christian', 'Jean-Michel', 'Joe et Mario', 'Joe', 'Magma', 'Z. Un album', 'Duplantier', 'Joe', 'Mario', 'Magma', 'Canal+', 'Arte', 'Rodolphe Escher', 'Télérama \n À Écouter', 'Magma', 'Gojira', 'CD Warner']
avec enthousiasme dès la fin mars par le magazine américain Rolling Stone comme un événement mondial. Car, en vingt ans de
------------------------
6999
['Showtunes Lambchop', 'Kurt Wagner', 'Lambchop', 'Trip', 'Wagner', 'Drop C', 'Fuku', 'Impossible Meatballs', 'Papa Was', 'Rolling', 'Lambchop', 'Kurt', 'François Gorin', 'City Slang']
ou potaches pour « boomers » ( Papa Was a Rolling Stone Journalist ). Tout cela sans jamais perdre la fibre
------------------------
9033
['Linda McCartney', 'Linda McCartney', 'Linda Eastman', 'Madmen', 'Beatles', 'Logique', 'Sir Paul McCartney', 'Mary', 'Paul and Heather', 'Scotland', 'Hissé', 'Paul', 'Gilles Mora', 'McCartney', 'Mary', 'Paul McCartney', 'Ram', 'post-Beatles', 'Paul', 'Linda McCartney', 'Bain', 'Mary', 'Blankit', 'Shadow', 'Lucky Spot', 'Paul', 'Willem de Kooning', 'Linda Eastman', 'Paul', 'Beatles', 'Stella McCartney', 'Linda McCartney', 'Life in Photo-', 'Taschen', 'Privilège inconfortable', 'Paola Genone', 'Flo', 'Polaroïd', 'Town and Country', 'Linda', 'Rolling Stones', 'SS Sea Panther', 'Linda Eastman', 'Brian Jones', 'Mick Jagger', 'Eric Clapton', 'Rolling', 'Linda', 'Frank Zappa', 'Jimi Hendrix', 'Janis Joplin', 'Jim Morrison', 'John Lennon', 'Exposition Linda McCartney']
Linda dérobe une invitation pour une réception en l'honneur des Rolling Stones à bord du SS Sea Panther amarré sur l'Hudson
------------------------
9033
['Linda McCartney', 'Linda McCartney', 'Linda Eastman', 'Madmen', 'Beatles', 'Logique', 'Sir Paul McCartney', 'Mary', 'Paul and Heather', 'Scotland', 'Hissé', 'Paul', 'Gilles Mora', 'McCartney', 'Mary', 'Paul McCartney', 'Ram', 'post-Beatles', 'Paul', 'Linda McCartney', 'Bain', 'Mary', 'Blankit', 'Shadow', 'Lucky Spot', 'Paul', 'Willem de Kooning', 'Linda Eastman', 'Paul', 'Beatles', 'Stella McCartney', 'Linda McCartney', 'Life in Photo-', 'Taschen', 'Privilège inconfortable', 'Paola Genone', 'Flo', 'Polaroïd', 'Town and Country', 'Linda', 'Rolling Stones', 'SS Sea Panther', 'Linda Eastman', 'Brian Jones', 'Mick Jagger', 'Eric Clapton', 'Rolling', 'Linda', 'Frank Zappa', 'Jimi Hendrix', 'Janis Joplin', 'Jim Morrison', 'John Lennon', 'Exposition Linda McCartney']
Eric Clapton est tout neuf sur la couverture du magazine Rolling Stone que Linda est la première femme à décrocher le
------------------------
9667
["Chronique d'une banlieue ordinaire", 'Lycéenne', 'Stéphanie', 'Doria Achour', 'Aure Atika', 'Marc Lavoine', 'Stéphanie', 'Envole-moi,', 'Jean-Jacques Goldman', 'Victor Hugo', 'Maupassant', 'Rabah', 'Shakespeare', 'Fatima', 'Soumaye Bocoum', 'Sylvie Ohayon', 'Papa Was Not a Rolling Stone', 'Robert Laffont', 'Sylvie Verheyde', 'Personnages attachants\n\nInfluencée', 'Jean Becker', 'Billy Elliot', 'La Fièvre du samedi soir', 'Sylvie Ohayon', 'Stéphanie', 'Cosette de La Courneuve', 'Juliette de Roméo', 'Stéphanie-Fatima', 'Stéphanie', 'Doria Achour', "L'École pour tous", 'Éric Rochant', 'Soumaye Bocoum', 'jean', 'Aure Atika', 'Stéphanie', 'Marc Lavoine', 'Sylvie Ohayon', 'Regardez-moi', 'Wonderbra', 'Goldman', 'Papa Was Not', 'Rolling', 'Comédie', 'Sylvie Ohayon', 'Doria Achour', 'Aura Atika', 'Figaro']
ce qui a donné le livre Papa Was Not a Rolling Stone (Robert Laffont, prix de la Closerie des Lilas 2011).
------------------------
9667
["Chronique d'une banlieue ordinaire", 'Lycéenne', 'Stéphanie', 'Doria Achour', 'Aure Atika', 'Marc Lavoine', 'Stéphanie', 'Envole-moi,', 'Jean-Jacques Goldman', 'Victor Hugo', 'Maupassant', 'Rabah', 'Shakespeare', 'Fatima', 'Soumaye Bocoum', 'Sylvie Ohayon', 'Papa Was Not a Rolling Stone', 'Robert Laffont', 'Sylvie Verheyde', 'Personnages attachants\n\nInfluencée', 'Jean Becker', 'Billy Elliot', 'La Fièvre du samedi soir', 'Sylvie Ohayon', 'Stéphanie', 'Cosette de La Courneuve', 'Juliette de Roméo', 'Stéphanie-Fatima', 'Stéphanie', 'Doria Achour', "L'École pour tous", 'Éric Rochant', 'Soumaye Bocoum', 'jean', 'Aure Atika', 'Stéphanie', 'Marc Lavoine', 'Sylvie Ohayon', 'Regardez-moi', 'Wonderbra', 'Goldman', 'Papa Was Not', 'Rolling', 'Comédie', 'Sylvie Ohayon', 'Doria Achour', 'Aura Atika', 'Figaro']
Le message principal du film. « Papa Was Not a Rolling Stone » Comédie dramatique de Sylvie Ohayon Avec Doria Achour,
------------------------
10311
['Silence', 'François Forestier', 'Grover Lewis', 'Rolling', 'Nouveau Journalisme', 'Grover Lewis', 'La Dernière Séance', 'Jeff Bridges', 'Bogdanovich', 'Guet-apens', 'Steve McQueen', 'Ali MacGraw', 'Peckinpah', 'Grover Lewis', 'Robert Mitchum', "Copains d'Eddie Coyle", 'Volkswagen', 'Grover', 'Stacy Keach', "Vol au-dessus d'un nid de coucou", 'Grover', 'Milos Forman', 'San Pedro', 'Danny DeVito', 'Nicholson', 'Hugh Hefner', 'Onassis', 'Détournement', 'Forestier', "L'Obs", 'Ce monsieur', "L'amour l'après-midi vaut le détour", 'Penélope Cruz', "L'Empire des sens", 'Cannes', 'Dennis Hopper', 'Marion Cotillard', 'Batman', 'James Bond', 'Laura Mars', 'Libération', 'Forestier', 'Le Cinéma infiltré', 'Grover Lewis', 'Capricci', "C'est de la daube !", 'François Forestier', 'Chiflet & Cie']
des pages. Il y avait de la place dans le Rolling Stone des années 1970. C'était le bon temps. Le Nouveau
------------------------
16905
['Joni Mitchell', 'Joni Michell', 'Ralentie', 'Song to a Seagull', 'David Crosby', 'CFQC AM', 'Roberta Joan Anderson', 'Mitchell', 'Si', 'Elliot Roberts', 'Neil Young', 'Joni Mitchell', 'Rolling', 'Cameron Crowe', 'Joni Mitchell', 'NUC', 'Joni Mitchell Archives - Vol. 1', 'The Early Years', 'Rhino', 'Warner']
la première fois. Une interview inédite avec l'ancien journaliste de Rolling Stone Cameron Crowe, devenu réalisateur de cinéma, offre un précieux
------------------------
21430
['Good Vibrations', 'Beach Boys', 'Beach Boys', 'Good Vibrations', 'Beatles', 'Brian Wilson', 'Graal', 'Mojo', 'Good Vibrations', 'Gold Star Studio', 'Brian Wilson', 'Pet Sounds', 'Beach Boys', 'Brian', 'Dennis', 'Carl', 'Mike Love', 'Al Jardine', 'Pendleton', 'Pendletones', 'I Get Around', 'Barbara Ann', 'Pet Sounds', 'Brian', 'Good Vibrations', 'Brian', 'The beach boys -good vibrations\n\n', 'Brian Wilson', 'Brian', 'Good Vibrations', 'Wilson', 'Brian', 'Eclipse', 'Good Vibrations', 'Pet Sounds', 'Brian Wilson', 'Beach Boys', 'Beach Boys', 'Kokomo', 'Good Vibrations', 'RTL', 'Nocturnes', 'Jean-François Johann', 'Like', 'Rolling', 'Bob Dylan']
Nocturnes, présentées par Jean-François Johann. La semaine prochaine, Like a Rolling Stone de Bob Dylan.
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
«Like a Rolling Stone», sous les pavés… Dylan . Bob Dylan a écrit
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
Dylan . Bob Dylan a écrit et composé Like a Rolling Stone en juin 1965 afin que, deux ans plus tard,
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
subitement. Le troisième morceau, toutes distorsions coupées, est Like a Rolling Stone. De la composition dylanienne, jamais n'a été donnée une
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
que grâce et gaîté (1). Bob Dylan - Like A Rolling Stone 1966 Tournée. Pourtant, il n'y a rien de gai
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
Pourtant, il n'y a rien de gai dans Like a Rolling Stone, histoire d'une jeune bourgeoise qui a dégringolé dans la
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
With no direction home/ Like a complete unknown/ Like a rolling stone ?» dit le refrain. Une pierre qui roule, en
------------------------
21489
['Like', 'Rolling', 'Dylan', 'Bob Dylan', 'Like', 'Rolling', 'Jimi Hendrix', 'Monterey Pop Festival', 'Who', 'My Generation', 'Hendrix', 'Killing Floor', 'Foxy Lady', 'Like', 'Rolling Stone', "summer of love - l'invraisemblable", 'Hendrix', 'Bob Dylan - Like A Rolling', 'Like', 'Rolling Stone', 'Dylan', 'Jagger', 'Richards', 'Nineteenth Nervous Breakdown', 'Under my Thumb', 'Hendrix', 'Dylan', 'Like', 'Like', 'Stones', 'Dylan', 'Dylan', 'Playboy', 'Like', 'Rolling', '»\n\nPoème', 'Dylan', 'Saturday Evening Post', 'How does it feel', 'Al Kooper', 'orgue Hammond', 'Highway 61 Revisited -', 'Dylan', 'Greil Marcus', 'Like', 'Rolling', 'Dylan', 'Rolling', 'Rolling Stones', 'Johnny Winter', 'Susheela Raman', 'Jimi Hendrix', 'Live at Monterey', 'Universal Music', 'Like', 'Rolling', 'Bob Dylan', 'Galaade', 'Like', 'Rolling Stone', 'RTL', 'Nocturnes', 'Jean-François Johann\n\nLa', 'The House of the Rising Sun', 'The Animals']
allait mal, tout était monotone et terne… Mais Like a Rolling Stone a changé tout ça. Je me suis retrouvé, je
------------------------
21489

In [76]:
df = ents
len(df)

408677

In [98]:
df = ents

# normalize both texts
def clean_text(text):
    text = text.lower()
    text = unicodedata.normalize("NFKD", text)
    text = unidecode(text) # remove accents
    # text = text.replace("\xa0", " ")
    text = text.strip()
    return text


df = df[df["name"].map(len) > 2] # short names

df["name"] = df["name"].apply(clean_text)

### check names with many tokens

maybe leave for now, if we do strict matching they'll be dropped anyway

In [103]:
df = df.drop_duplicates(subset=["name"])
df.reset_index()

         index  name_id            name  name_count  article_id
0            2        3      liberation        3336         870
1            3        4          figaro        2749        1786
2            4        5        internet        2376          40
3            5        6          mozart        1831          87
4            6        7            dieu        1616         592
...        ...      ...             ...         ...         ...
386005  408671   408672    i'm changing           1       49038
386006  408672   408673       i'm blind           1       48689
386007  408673   408674     i'm amazing           1       49542
386008  408674   408675  i'm all smiles           1       50227
386009  408676   408677   i'll show you           1       49669

[386010 rows x 5 columns]

In [105]:
df.to_csv("/Users/pol/Downloads/extracted_ents_clean.csv", sep=';')